// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IProductMueblesFields {
  /** Title */
  title: string;

  /** Title Slug */
  titleSlug: string;

  /** Category */
  category:
    | "armarios"
    | "auxiliar"
    | "butacas"
    | "comedor"
    | "dormitorios"
    | "juvenil"
    | "salones"
    | "sofas";

  /** Images */
  images: Asset[];

  /** Materials */
  materials?: string[] | undefined;

  /** Is Oferta */
  isOferta: "oferta" | "normal";

  /** Price */
  price?: number | undefined;

  /** Price Before */
  priceBefore?: number | undefined;

  /** Description */
  description?: Document | undefined;
}

export interface IProductMuebles extends Entry<IProductMueblesFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "productMuebles";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "productMuebles";

export type IEntry = IProductMuebles;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
